// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (uploader_id, filename, original_name, mime_type, size_bytes, storage_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uploader_id, filename, original_name, mime_type, size_bytes, storage_path, created_at
`

type CreateMediaParams struct {
	UploaderID   pgtype.UUID `json:"uploader_id"`
	Filename     string      `json:"filename"`
	OriginalName string      `json:"original_name"`
	MimeType     string      `json:"mime_type"`
	SizeBytes    int64       `json:"size_bytes"`
	StoragePath  string      `json:"storage_path"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.UploaderID,
		arg.Filename,
		arg.OriginalName,
		arg.MimeType,
		arg.SizeBytes,
		arg.StoragePath,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media
WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, uploader_id, filename, original_name, mime_type, size_bytes, storage_path, created_at FROM media
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}
