// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RoomStatus string

const (
	RoomStatusDraft  RoomStatus = "draft"
	RoomStatusActive RoomStatus = "active"
	RoomStatusClosed RoomStatus = "closed"
)

func (e *RoomStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomStatus(s)
	case string:
		*e = RoomStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomStatus: %T", src)
	}
	return nil
}

type NullRoomStatus struct {
	RoomStatus RoomStatus `json:"room_status"`
	Valid      bool       `json:"valid"` // Valid is true if RoomStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RoomStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomStatus), nil
}

type RoomType string

const (
	RoomTypeSingleChoice   RoomType = "single_choice"
	RoomTypeMultipleChoice RoomType = "multiple_choice"
)

func (e *RoomType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomType(s)
	case string:
		*e = RoomType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomType: %T", src)
	}
	return nil
}

type NullRoomType struct {
	RoomType RoomType `json:"room_type"`
	Valid    bool     `json:"valid"` // Valid is true if RoomType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomType) Scan(value interface{}) error {
	if value == nil {
		ns.RoomType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomType), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Medium struct {
	ID           pgtype.UUID        `json:"id"`
	UploaderID   pgtype.UUID        `json:"uploader_id"`
	Filename     string             `json:"filename"`
	OriginalName string             `json:"original_name"`
	MimeType     string             `json:"mime_type"`
	SizeBytes    int64              `json:"size_bytes"`
	StoragePath  string             `json:"storage_path"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Option struct {
	ID          pgtype.UUID        `json:"id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	Label       string             `json:"label"`
	Description pgtype.Text        `json:"description"`
	Metadata    []byte             `json:"metadata"`
	MediaID     pgtype.UUID        `json:"media_id"`
	OrderNum    int32              `json:"order_num"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID           pgtype.UUID        `json:"id"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Type         RoomType           `json:"type"`
	Status       RoomStatus         `json:"status"`
	ShowRealtime bool               `json:"show_realtime"`
	MaxVotes     int32              `json:"max_votes"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	ShareCode    string             `json:"share_code"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         UserRole           `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Vote struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	OptionID  pgtype.UUID        `json:"option_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
