// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: options.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOption = `-- name: CreateOption :one
INSERT INTO options (room_id, label, description, metadata, media_id, order_num)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, room_id, label, description, metadata, media_id, order_num, created_at
`

type CreateOptionParams struct {
	RoomID      pgtype.UUID `json:"room_id"`
	Label       string      `json:"label"`
	Description pgtype.Text `json:"description"`
	Metadata    []byte      `json:"metadata"`
	MediaID     pgtype.UUID `json:"media_id"`
	OrderNum    int32       `json:"order_num"`
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, createOption,
		arg.RoomID,
		arg.Label,
		arg.Description,
		arg.Metadata,
		arg.MediaID,
		arg.OrderNum,
	)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Label,
		&i.Description,
		&i.Metadata,
		&i.MediaID,
		&i.OrderNum,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOption = `-- name: DeleteOption :exec
DELETE FROM options
WHERE id = $1
`

func (q *Queries) DeleteOption(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOption, id)
	return err
}

const getOptionByID = `-- name: GetOptionByID :one
SELECT id, room_id, label, description, metadata, media_id, order_num, created_at FROM options
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOptionByID(ctx context.Context, id pgtype.UUID) (Option, error) {
	row := q.db.QueryRow(ctx, getOptionByID, id)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Label,
		&i.Description,
		&i.Metadata,
		&i.MediaID,
		&i.OrderNum,
		&i.CreatedAt,
	)
	return i, err
}

const listOptionsByRoom = `-- name: ListOptionsByRoom :many
SELECT id, room_id, label, description, metadata, media_id, order_num, created_at FROM options
WHERE room_id = $1
ORDER BY order_num ASC, created_at ASC
`

func (q *Queries) ListOptionsByRoom(ctx context.Context, roomID pgtype.UUID) ([]Option, error) {
	rows, err := q.db.Query(ctx, listOptionsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Option{}
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Label,
			&i.Description,
			&i.Metadata,
			&i.MediaID,
			&i.OrderNum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
