// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	DeleteMedia(ctx context.Context, id pgtype.UUID) error
	DeleteOption(ctx context.Context, id pgtype.UUID) error
	DeleteRoom(ctx context.Context, arg DeleteRoomParams) error
	GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error)
	GetOptionByID(ctx context.Context, id pgtype.UUID) (Option, error)
	GetOptionsCountByRoom(ctx context.Context, roomID pgtype.UUID) (int64, error)
	GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error)
	GetRoomByShareCode(ctx context.Context, shareCode string) (Room, error)
	GetTotalVotesByRoom(ctx context.Context, roomID pgtype.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetVoteByRoomUserOption(ctx context.Context, arg GetVoteByRoomUserOptionParams) (Vote, error)
	GetVoteCountByRoomAndUser(ctx context.Context, arg GetVoteCountByRoomAndUserParams) (int64, error)
	GetVotesByRoomAndUser(ctx context.Context, arg GetVotesByRoomAndUserParams) ([]Vote, error)
	ListOptionsByRoom(ctx context.Context, roomID pgtype.UUID) ([]Option, error)
	ListRoomsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Room, error)
	UpdateOption(ctx context.Context, arg UpdateOptionParams) (Option, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (Room, error)
}

var _ Querier = (*Queries)(nil)
