// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (owner_id, title, description, type, show_realtime, max_votes, starts_at, ends_at, share_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_id, title, description, type, status, show_realtime, max_votes, starts_at, ends_at, share_code, created_at, updated_at
`

type CreateRoomParams struct {
	OwnerID      pgtype.UUID        `json:"owner_id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Type         RoomType           `json:"type"`
	ShowRealtime bool               `json:"show_realtime"`
	MaxVotes     int32              `json:"max_votes"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	ShareCode    string             `json:"share_code"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.ShowRealtime,
		arg.MaxVotes,
		arg.StartsAt,
		arg.EndsAt,
		arg.ShareCode,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.ShowRealtime,
		&i.MaxVotes,
		&i.StartsAt,
		&i.EndsAt,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE id = $1 AND owner_id = $2
`

type DeleteRoomParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) error {
	_, err := q.db.Exec(ctx, deleteRoom, arg.ID, arg.OwnerID)
	return err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, owner_id, title, description, type, status, show_realtime, max_votes, starts_at, ends_at, share_code, created_at, updated_at FROM rooms
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.ShowRealtime,
		&i.MaxVotes,
		&i.StartsAt,
		&i.EndsAt,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByShareCode = `-- name: GetRoomByShareCode :one
SELECT id, owner_id, title, description, type, status, show_realtime, max_votes, starts_at, ends_at, share_code, created_at, updated_at FROM rooms
WHERE share_code = $1
LIMIT 1
`

func (q *Queries) GetRoomByShareCode(ctx context.Context, shareCode string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByShareCode, shareCode)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.ShowRealtime,
		&i.MaxVotes,
		&i.StartsAt,
		&i.EndsAt,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoomsByOwner = `-- name: ListRoomsByOwner :many
SELECT id, owner_id, title, description, type, status, show_realtime, max_votes, starts_at, ends_at, share_code, created_at, updated_at FROM rooms
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRoomsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.ShowRealtime,
			&i.MaxVotes,
			&i.StartsAt,
			&i.EndsAt,
			&i.ShareCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET
    title = $2,
    description = $3,
    show_realtime = $4,
    max_votes = $5,
    starts_at = $6,
    ends_at = $7,
    updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, owner_id, title, description, type, status, show_realtime, max_votes, starts_at, ends_at, share_code, created_at, updated_at
`

type UpdateRoomParams struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	ShowRealtime bool               `json:"show_realtime"`
	MaxVotes     int32              `json:"max_votes"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ShowRealtime,
		arg.MaxVotes,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.ShowRealtime,
		&i.MaxVotes,
		&i.StartsAt,
		&i.EndsAt,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoomStatus = `-- name: UpdateRoomStatus :one
UPDATE rooms
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, description, type, status, show_realtime, max_votes, starts_at, ends_at, share_code, created_at, updated_at
`

type UpdateRoomStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status RoomStatus  `json:"status"`
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomStatus, arg.ID, arg.Status)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.ShowRealtime,
		&i.MaxVotes,
		&i.StartsAt,
		&i.EndsAt,
		&i.ShareCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
