// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVote = `-- name: CreateVote :one
INSERT INTO votes (room_id, user_id, option_id)
VALUES ($1, $2, $3)
RETURNING id, room_id, user_id, option_id, created_at
`

type CreateVoteParams struct {
	RoomID   pgtype.UUID `json:"room_id"`
	UserID   pgtype.UUID `json:"user_id"`
	OptionID pgtype.UUID `json:"option_id"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote, arg.RoomID, arg.UserID, arg.OptionID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.OptionID,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalVotesByRoom = `-- name: GetTotalVotesByRoom :one
SELECT COUNT(*) AS total
FROM votes
WHERE room_id = $1
`

func (q *Queries) GetTotalVotesByRoom(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalVotesByRoom, roomID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getVoteByRoomAndUser = `-- name: GetVoteByRoomAndUser :one
SELECT id, room_id, user_id, option_id, created_at FROM votes
WHERE room_id = $1 AND user_id = $2
LIMIT 1
`

type GetVoteByRoomAndUserParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetVoteByRoomAndUser(ctx context.Context, arg GetVoteByRoomAndUserParams) (Vote, error) {
	row := q.db.QueryRow(ctx, getVoteByRoomAndUser, arg.RoomID, arg.UserID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.OptionID,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteCountsByRoom = `-- name: GetVoteCountsByRoom :many
SELECT
    option_id,
    COUNT(*) AS vote_count
FROM votes
WHERE room_id = $1
GROUP BY option_id
`

type GetVoteCountsByRoomRow struct {
	OptionID  pgtype.UUID `json:"option_id"`
	VoteCount int64       `json:"vote_count"`
}

func (q *Queries) GetVoteCountsByRoom(ctx context.Context, roomID pgtype.UUID) ([]GetVoteCountsByRoomRow, error) {
	rows, err := q.db.Query(ctx, getVoteCountsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVoteCountsByRoomRow{}
	for rows.Next() {
		var i GetVoteCountsByRoomRow
		if err := rows.Scan(&i.OptionID, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
