// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVote = `-- name: CreateVote :one
INSERT INTO votes (room_id, user_id, option_id)
VALUES ($1, $2, $3)
RETURNING id, room_id, user_id, option_id, created_at
`

type CreateVoteParams struct {
	RoomID   pgtype.UUID `json:"room_id"`
	UserID   pgtype.UUID `json:"user_id"`
	OptionID pgtype.UUID `json:"option_id"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote, arg.RoomID, arg.UserID, arg.OptionID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.OptionID,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalVotesByRoom = `-- name: GetTotalVotesByRoom :one
SELECT COUNT(*) AS total
FROM votes
WHERE room_id = $1
`

func (q *Queries) GetTotalVotesByRoom(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalVotesByRoom, roomID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getVoteByRoomUserOption = `-- name: GetVoteByRoomUserOption :one
SELECT id, room_id, user_id, option_id, created_at FROM votes
WHERE room_id = $1 AND user_id = $2 AND option_id = $3
LIMIT 1
`

type GetVoteByRoomUserOptionParams struct {
	RoomID   pgtype.UUID `json:"room_id"`
	UserID   pgtype.UUID `json:"user_id"`
	OptionID pgtype.UUID `json:"option_id"`
}

func (q *Queries) GetVoteByRoomUserOption(ctx context.Context, arg GetVoteByRoomUserOptionParams) (Vote, error) {
	row := q.db.QueryRow(ctx, getVoteByRoomUserOption, arg.RoomID, arg.UserID, arg.OptionID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.OptionID,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteCountByRoomAndUser = `-- name: GetVoteCountByRoomAndUser :one
SELECT COUNT(*) AS total
FROM votes
WHERE room_id = $1 AND user_id = $2
`

type GetVoteCountByRoomAndUserParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetVoteCountByRoomAndUser(ctx context.Context, arg GetVoteCountByRoomAndUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, getVoteCountByRoomAndUser, arg.RoomID, arg.UserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getVotesByRoomAndUser = `-- name: GetVotesByRoomAndUser :many
SELECT id, room_id, user_id, option_id, created_at FROM votes
WHERE room_id = $1 AND user_id = $2
`

type GetVotesByRoomAndUserParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetVotesByRoomAndUser(ctx context.Context, arg GetVotesByRoomAndUserParams) ([]Vote, error) {
	rows, err := q.db.Query(ctx, getVotesByRoomAndUser, arg.RoomID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vote{}
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.OptionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
