// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Alberd Juniawan Pasunda",
            "url": "https://github.com/alberdjuniawan",
            "email": "alberd@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user with email and password, returning JWT access and refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully logged in",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_auth.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Invalid email or password",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the profile information of the currently authenticated user based on the provided JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "User profile retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_auth.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user account and returns authentication tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully registered",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_auth.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input data or validation error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "Email already exists",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/media": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Uploads an image file (jpeg, png, webp) up to 5MB to MinIO and returns the media details. Requires authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Upload media file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "File successfully uploaded",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_media.MediaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid file, missing field, or file too large",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/media/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a specific media file by its ID. Only the original uploader is authorized to delete it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Delete media file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Media ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden, you are not the uploader",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Media not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rooms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of all voting rooms created by the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "List user's rooms",
                "responses": {
                    "200": {
                        "description": "List of rooms retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_modules_room.RoomResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new voting room with specific configurations. The caller automatically becomes the room owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "Create a new voting room",
                "parameters": [
                    {
                        "description": "Room creation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_room.CreateRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Room successfully created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_room.RoomResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input or max votes",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error or share code collision",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rooms/share/{code}": {
            "get": {
                "description": "Public endpoint to retrieve room details using its unique short share code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "Get room details by share code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Share Code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Room details retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_room.RoomResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rooms/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the full details of a specific voting room using its UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "Get room details by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Room details retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_room.RoomResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently deletes a room. Only the room owner can perform this action.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "Delete a room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden, you are not the room owner",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rooms/{id}/leaderboard": {
            "get": {
                "description": "Retrieves the real-time leaderboard and vote counts for a specific voting room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leaderboard"
                ],
                "summary": "Get room leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Leaderboard retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_leaderboard.LeaderboardResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rooms/{id}/options": {
            "get": {
                "description": "Retrieves all voting options associated with a specific room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "option"
                ],
                "summary": "List room options",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Options retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_modules_option.OptionResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a new option to a specific room. The room must be in \"draft\" status and the caller must be the room owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "option"
                ],
                "summary": "Create a new voting option",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Option details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_option.CreateOptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Option successfully created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_option.OptionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input or room is not in draft status",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden, you are not the room owner",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rooms/{id}/options/{optionId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a specific option. The room must be in \"draft\" status and the caller must be the room owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "option"
                ],
                "summary": "Delete an option",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Option ID (UUID)",
                        "name": "optionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Room is not in draft status",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden, you are not the room owner",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Option not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the details of a specific option. The room must be in \"draft\" status and the caller must be the room owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "option"
                ],
                "summary": "Update an option",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Option ID (UUID)",
                        "name": "optionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Option update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_option.UpdateOptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Option successfully updated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_option.OptionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input or room is not in draft status",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden, you are not the room owner",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Option not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rooms/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the status of a room (e.g., from draft to active). Only the room owner can perform this action.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "room"
                ],
                "summary": "Update room status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_room.UpdateRoomStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Room status updated successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_room.RoomResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid status transition",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden, you are not the room owner",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rooms/{id}/votes": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows an authenticated user to cast a vote for a specific option in a room. Handles both single and multiple choice limits.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vote"
                ],
                "summary": "Cast a vote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vote details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_vote.CastVoteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Vote successfully cast",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_vote.VoteResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input or option does not belong to the room",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Voting is closed or max votes reached",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Room or option not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "Already voted in this room or for this option",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/rooms/{id}/votes/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the authenticated user's voting record and status for a specific room.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vote"
                ],
                "summary": "Get my vote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User's vote retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_modules_vote.MyVoteResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Access denied, invalid or expired token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ws/rooms/{id}": {
            "get": {
                "description": "Upgrades the HTTP connection to a WebSocket connection. Used to receive real-time updates for a specific voting room (e.g., live vote counts).",
                "tags": [
                    "realtime"
                ],
                "summary": "Connect to Room WebSocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols (WebSocket connection established)"
                    },
                    "400": {
                        "description": "Room ID is required",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_alberdjuniawan_votesystem_internal_shared_response.WebResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_alberdjuniawan_votesystem_internal_shared_response.ErrorDetail"
                },
                "meta": {},
                "request_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_modules_auth.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/internal_modules_auth.UserResponse"
                }
            }
        },
        "internal_modules_auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_modules_auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 2
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "internal_modules_auth.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "internal_modules_leaderboard.LeaderboardResponse": {
            "type": "object",
            "properties": {
                "room_id": {
                    "type": "string"
                },
                "scores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_modules_leaderboard.OptionScore"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_modules_leaderboard.OptionScore": {
            "type": "object",
            "properties": {
                "option_id": {
                    "type": "string"
                },
                "vote_count": {
                    "type": "integer"
                }
            }
        },
        "internal_modules_media.MediaResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "original_name": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_modules_option.CreateOptionRequest": {
            "type": "object",
            "required": [
                "label"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "label": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "media_id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "order_num": {
                    "type": "integer"
                }
            }
        },
        "internal_modules_option.OptionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "media_id": {
                    "type": "string"
                },
                "media_url": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "order_num": {
                    "type": "integer"
                },
                "room_id": {
                    "type": "string"
                }
            }
        },
        "internal_modules_option.UpdateOptionRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "label": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "media_id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "order_num": {
                    "type": "integer"
                }
            }
        },
        "internal_modules_room.CreateRoomRequest": {
            "type": "object",
            "required": [
                "title",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "ends_at": {
                    "type": "string"
                },
                "max_votes": {
                    "type": "integer",
                    "minimum": 1
                },
                "show_realtime": {
                    "type": "boolean"
                },
                "starts_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "single_choice",
                        "multiple_choice"
                    ]
                }
            }
        },
        "internal_modules_room.RoomResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "ends_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "max_votes": {
                    "type": "integer"
                },
                "owner_id": {
                    "type": "string"
                },
                "share_code": {
                    "type": "string"
                },
                "share_url": {
                    "type": "string"
                },
                "show_realtime": {
                    "type": "boolean"
                },
                "starts_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_modules_room.UpdateRoomStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "draft",
                        "active",
                        "closed"
                    ]
                }
            }
        },
        "internal_modules_vote.CastVoteRequest": {
            "type": "object",
            "required": [
                "option_id"
            ],
            "properties": {
                "option_id": {
                    "type": "string"
                }
            }
        },
        "internal_modules_vote.MyVoteResponse": {
            "type": "object",
            "properties": {
                "has_voted": {
                    "type": "boolean"
                },
                "room_id": {
                    "type": "string"
                },
                "room_type": {
                    "type": "string"
                },
                "votes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_modules_vote.VoteResponse"
                    }
                }
            }
        },
        "internal_modules_vote.VoteResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "option_id": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "VoteSystem API",
	Description:      "API documentation for the VoteSystem platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
